server:
  command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8001"
http:
  address: "0.0.0.0:8001"
  workers:
    command: "php artisan octane:start --server=roadrunner"
    pool:
      numWorkers: 4
